// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPNLv-ecS6aCEgkV05q5UWQvDzCFkT7E',
    appId: '1:217302502615:web:51e42cf83722fba2b7f492',
    messagingSenderId: '217302502615',
    projectId: 'exampl-be8d5',
    authDomain: 'exampl-be8d5.firebaseapp.com',
    storageBucket: 'exampl-be8d5.appspot.com',
    measurementId: 'G-LVQK47GSLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPP7_ZfRkcBk5cKz7MqX_zUc8UvPcmiMo',
    appId: '1:217302502615:android:02f2755c8a3b2ca7b7f492',
    messagingSenderId: '217302502615',
    projectId: 'exampl-be8d5',
    storageBucket: 'exampl-be8d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGkYM57dW4rOvyFQ79IwN4jPPNqEtZhJc',
    appId: '1:217302502615:ios:59ada5b639288b81b7f492',
    messagingSenderId: '217302502615',
    projectId: 'exampl-be8d5',
    storageBucket: 'exampl-be8d5.appspot.com',
    iosBundleId: 'com.example.medicineremindertrialapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGkYM57dW4rOvyFQ79IwN4jPPNqEtZhJc',
    appId: '1:217302502615:ios:59ada5b639288b81b7f492',
    messagingSenderId: '217302502615',
    projectId: 'exampl-be8d5',
    storageBucket: 'exampl-be8d5.appspot.com',
    iosBundleId: 'com.example.medicineremindertrialapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADPNLv-ecS6aCEgkV05q5UWQvDzCFkT7E',
    appId: '1:217302502615:web:5aedf66da6c96d4db7f492',
    messagingSenderId: '217302502615',
    projectId: 'exampl-be8d5',
    authDomain: 'exampl-be8d5.firebaseapp.com',
    storageBucket: 'exampl-be8d5.appspot.com',
    measurementId: 'G-CELEQ6H51W',
  );
}
